# Generated by Django 5.0.6 on 2024-06-28 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_visit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
