# Generated by Django 5.0.6 on 2024-06-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AlterField(
            model_name='businessuser',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
