# Generated by Django 5.0.6 on 2024-06-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customer_address_alter_businessuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
