# Generated by Django 5.0.6 on 2024-06-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_businessuser_managers_businessuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.IntegerField(default=30, help_text='Duration in minutes'),
        ),
    ]
